---

- name: Provisioning
  hosts: all
  become: true
#  vars_files:
#    - vars/main.yml
  roles:
    - ansible-role-nginx-master
#    - geerlingguy.apache
#    - geerlingguy.nodejs

  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes

  tasks:
    - file:
        path: /var/www/html
        owner: ubuntu
        group: ubuntu
